--- #YAML:1.0
name:               WWW-HtmlUnit-Spidey
version:            0.01
abstract:           A mostly declarative language and tools for writing web
author:
    - Antonio Bonifati <ninuzzo@cpan.org>
license:            apache2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Parse:    0
    Log::Log4perl:  1.2
    MIME::Types:    1.31
    Switch:         0
    Test::More:     0
    WWW::HtmlUnit:  0.15
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
